#pragma once

#include <map>
#include <string>

namespace camus
{
	struct config {
		std::string posts_directory;
		std::string out_directory;
		std::string assets_directory;
		std::string filename_type;
		std::string markdown_engine;
		std::string site_title;
		std::string site_subtitle;
		std::string site_description;
		std::string home_template;
		std::string page_template;
	};

	class ini
	{
		std::string file_;

	  public:
		config config_ = {
			.posts_directory = "posts",
			.out_directory = "html",
			.assets_directory = "assets",
			.filename_type = "uuid",
			.markdown_engine = "gomarkdown",
			.site_title = "Just Another Camus blog",
			.site_subtitle = "Static blog generated by Camus",
			.site_description = "Rome was not built in one day.",
			.home_template = "theme/home.html",
			.page_template = "theme/page.html",
		};


		static ini &get();
		static config &all();
		static void fill(std::string &data);
		static std::string make_key(const std::string &section, const std::string &key);

		std::unordered_map<std::string, std::string> parse(const std::string &name);
		void write(const std::unordered_map<std::string, std::string> &config) const;
	};
} // namespace camus
