#pragma once

#include <map>
#include <string>

namespace camus
{
	struct config {
		bool sitemap;
		std::string posts_directory;
		std::string out_directory;
		std::string assets_directory;
		std::string filename_type;
		std::string markdown_engine;
		std::string home_template;
		std::string page_template;
		std::string site_homepage;
		std::string site_github_repo;
		std::string site_title;
		std::string site_subtitle;
		std::string site_description;
		const std::unordered_map<std::string, std::string> config_map;

		explicit config(const std::unordered_map<std::string, std::string> &data) : config_map(data)
		{
			sitemap = false;
			posts_directory = "posts";
			out_directory = "html";
			assets_directory = "assets";
			filename_type = "uuid";
			markdown_engine = "cmark";
			home_template = "theme/home.html";
			page_template = "theme/page.html";
			site_title = "Just Another Camus blog";
			site_subtitle = "Static blog generated by Camus";
			site_description = "Rome was not built in one day.";
			site_homepage = "";
			site_github_repo = "";

			if (data.contains("camus.posts_directory")) {
				posts_directory = data.at("camus.posts_directory");
			}

			if (data.contains("camus.assets_directory")) {
				assets_directory = data.at("camus.assets_directory");
			}

			if (data.contains("camus.out_directory")) {
				out_directory = data.at("camus.out_directory");
			}

			if (data.contains("camus.markdown_engine")) {
				markdown_engine = data.at("camus.markdown_engine");
			}

			if (data.contains("camus.filename_type")) {
				filename_type = data.at("camus.filename_type");
			}

			if (data.contains("site.title")) {
				site_title = data.at("site.title");
			}

			if (data.contains("site.description")) {
				site_description = data.at("site.description");
			}

			if (data.contains("site.subtitle")) {
				site_subtitle = data.at("site.subtitle");
			}

			if (data.contains("site.homepage")) {
				site_homepage = data.at("site.homepage");
			}

			if (data.contains("site.github_repo")) {
				site_github_repo = data.at("site.github_repo");
			}

			if (data.contains("site.sitemap")) {
				sitemap = data.at("site.sitemap") == "true";
			}
		}
	};

	class ini
	{
		std::string file_;
		config *config_ = nullptr;

	  public:
		static ini &get();
		static config all();
		static void fill(std::string &data);
		static std::string make_key(const std::string &section, const std::string &key);

		std::unordered_map<std::string, std::string> parse(const std::string &name);
		void write(const std::unordered_map<std::string, std::string> &config) const;
	};
} // namespace camus
