var normalizePath = function(p) {
    if (!p || p === '/') return '/';
    if (!p.startsWith('/')) p = '/' + p;
    if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
    return p;
};

var getParent = function(p) {
    var np = normalizePath(p);
    if (np === '/') return null;
    var parts = np.split('/');
    parts.pop();
    if (parts.length === 0 || (parts.length === 1 && parts[0] === '')) return '/';
    return parts.join('/');
};

var formatDate = function(ts) {
    var n = Number(ts);
    if (!n || isNaN(n)) return '';
    var d = new Date(n * 1000);
    if (isNaN(d.getTime())) return '';
    return d.getFullYear() + '-' +
        String(d.getMonth() + 1).padStart(2, '0') + '-' +
        String(d.getDate()).padStart(2, '0');
};

var tocData = [
    { desc: "Rome was not built in one day.", is_dir: true, path: "/", subtitle: "Static blog generated by Camus", title: "Just Another Camus blog", write_time: 1783846307 },
    { path: "/%E7%A4%BA%E4%BE%8B2.html", title: "示例2", write_time: 1783846307 },
    { desc: "Rome was not built in one day.", is_dir: true, path: "/dir1", subtitle: "Static blog generated by Camus", title: "Just Another Camus blog", write_time: 1742083200 },
    { link_path: "/s/item1.html", path: "/dir1/%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B.html", title: "第一个示例", write_time: 1742083200 },
    { desc: "Rome was not built in one day.", is_dir: true, path: "/dir1/dir2", subtitle: "Static blog generated by Camus", title: "Just Another Camus blog", write_time: 1742083200 },
    { link_path: "/s/f1c6.html", path: "/dir1/dir2/%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B.html", title: "第一个示例", write_time: 1742083200 },
    { link_path: "/s/b0d0.html", path: "/dir1/dir2/%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B.html", title: "第一个示例", write_time: 1742083200 },
    { link_path: "/s/cd29.html", path: "/dir1/%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B.html", title: "第一个示例", write_time: 1742083200 },
    { desc: "DIR0 description", is_dir: true, path: "/dest/first-dir", subtitle: "DIR0 subtitle", title: "DIR0", write_time: 1742083200 },
    { link_path: "/s/item2-1.html", path: "/dest/first-dir/%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B.html", title: "第一个示例", write_time: 1742083200 },
    { link_path: "/s/134e3.html", path: "/dest/first-dir/%E7%AC%AC%E4%B8%80%E4%B8%AA%E7%A4%BA%E4%BE%8B.html", title: "第一个示例", write_time: 1742083200 },
    { path: "/item1.html", title: "item1", write_time: 1783846307 }
];

var renderToc = function(flatData, dirParam) {
    var currentPath = normalizePath(dirParam || '/');
    var currentEntry = null;
    for (var i = 0; i < flatData.length; i++) {
        if (flatData[i].is_dir && normalizePath(flatData[i].path) === currentPath) {
            currentEntry = flatData[i];
            break;
        }
    }
    if (!currentEntry) currentPath = '/';
    if (!currentEntry) {
        for (var i = 0; i < flatData.length; i++) {
            if (flatData[i].is_dir && normalizePath(flatData[i].path) === '/') {
                currentEntry = flatData[i];
                break;
            }
        }
    }

    var items = [];
    var subDirs = [];
    var files = [];
    var pfx = currentPath === '/' ? '/' : currentPath + '/';

    for (var j = 0; j < flatData.length; j++) {
        var entry = flatData[j];
        var ep = normalizePath(entry.path);
        if (ep === currentPath) continue;
        if (!ep.startsWith(pfx)) continue;
        var remainder = ep.slice(pfx.length);
        if (remainder.indexOf('/') !== -1) continue;
        if (entry.is_dir) {
            subDirs.push(entry);
        } else {
            var link = entry.link_path || ep;
            files.push({ label: entry.title, url: normalizePath(link), time: formatDate(entry.write_time) });
        }
    }

    for (var k = 0; k < subDirs.length; k++) {
        var cdp = normalizePath(subDirs[k].path);
        var encodedPath = cdp.replace(/^\//, '');
        items.push({
            type: 'dir',
            label: subDirs[k].title,
            url: '/?dir=' + encodeURIComponent(encodedPath),
            time: formatDate(subDirs[k].write_time)
        });
    }

    for (var f = 0; f < files.length; f++) {
        items.push({ type: 'file', label: files[f].label, url: files[f].url, time: files[f].time });
    }

    return {
        currentPath: currentPath,
        entry: currentEntry,
        dirParam: dirParam,
        items: items
    };
};

var testPaths = ['', '/dir1', '/dir1/dir2', '/dest/first-dir', '/nonexistent'];
testPaths.forEach(function(path) {
    var result = renderToc(tocData, path);
    console.log('=== dir=' + JSON.stringify(path || '(none)') + ' (currentPath: ' + result.currentPath + ') ===');
    if (result.entry) {
        console.log('  Title: ' + result.entry.title);
        console.log('  Desc: ' + (result.entry.desc || '(none)'));
    }
    result.items.forEach(function(item) {
        console.log('  [' + item.type + '] ' + item.label + ' -> ' + item.url + ' (' + item.time + ')');
    });
    console.log('');
});

console.log('=== Flatten articles (page.html) ===');
var flattenArticles = function(flat) {
    var result = [];
    for (var i = 0; i < flat.length; i++) {
        if (!flat[i].is_dir) {
            result.push({
                url: normalizePath(flat[i].link_path || flat[i].path),
                display_name: flat[i].title,
                path: normalizePath(flat[i].path)
            });
        }
    }
    return result;
};

var articles = flattenArticles(tocData);
articles.forEach(function(a, i) {
    console.log('  ' + (i+1) + '. url=' + a.url + ' | path=' + a.path + ' | name=' + a.display_name);
});

console.log('');
console.log('=== Find parent path ===');
var findParentPath = function(flat, articleUrl) {
    var au = normalizePath(articleUrl);
    var articlePath = null;
    for (var i = 0; i < flat.length; i++) {
        if (!flat[i].is_dir) {
            var entryUrl = normalizePath(flat[i].link_path || flat[i].path);
            var entryPath = normalizePath(flat[i].path);
            if (entryUrl === au || entryPath === au) {
                articlePath = entryPath;
                break;
            }
        }
    }
    if (!articlePath) return '/';
    var bestMatch = null;
    var bestLen = 0;
    for (var i = 0; i < flat.length; i++) {
        if (flat[i].is_dir) {
            var dp = normalizePath(flat[i].path);
            var prefix = dp === '/' ? '/' : dp + '/';
            if (articlePath.startsWith(prefix)) {
                if (dp.length > bestLen) {
                    bestLen = dp.length;
                    bestMatch = dp;
                }
            }
        }
    }
    return bestMatch || '/';
};

console.log('  By url:');
articles.forEach(function(a) {
    console.log('    ' + a.url + ' -> parent: ' + findParentPath(tocData, a.url));
});
console.log('  By path:');
articles.forEach(function(a) {
    console.log('    ' + a.path + ' -> parent: ' + findParentPath(tocData, a.path));
});
