#pragma once

#include <string>
#include <unordered_map>

#include "common/filesystem/filesystem.h"
#include "yaml-cpp/yaml.h"

namespace camus
{
	struct site_toc_item {
		std::string dir_name;
		std::string title;

		std::string output_dir() const
		{
			return filesystem::clean_path(dir_name, ".");
		}

		std::string url_path() const
		{
			return filesystem::clean_path(dir_name, "/");
		}
	};

	struct site_conf {
		std::string title = "Just Another Camus blog";
		std::string subtitle = "Static blog generated by Camus";
		std::string description = "Rome was not built in one day.";
		std::string url = "https://github.com/o8x/camus";
		std::string repo = "https://github.com/o8x/camus";
		std::vector<site_toc_item> toc;

		[[nodiscard]] site_toc_item find_toc(const std::string &dir) const
		{
			for (const auto &it : toc) {
				if (it.dir_name == dir) {
					return it;
				}
			}

			return {};
		}
	};

	struct camus_conf {
		bool sitemap;
		std::string work_dir;
		std::string source_dir = "posts";
		std::string output_dir = "html";
		std::string assets_dir = "assets";
		std::string theme_home = "theme/default/home.html";
		std::string theme_page = "theme/default/page.html";
		std::string filename_case = "keep";
		std::string toc_format = "json";
	};

	class config
	{
		std::unordered_map<std::string, std::string> flattened_map;

	  public:
		camus_conf camus;
		site_conf site;

		explicit config(const YAML::Node &root);

		[[nodiscard]] std::unordered_map<std::string, std::string> map() const
		{
			return flattened_map;
		}
	};

	class conf_loader
	{
		std::string file_;
		config *config_ = nullptr;

	  public:
		static conf_loader &get();
		static camus_conf camus();
		static site_conf site();
		static std::string render_var(const std::string &data);

		void parse_yaml(const std::string &filename);
	};

} // namespace camus
