name: CMake on multiple platforms

on:
    push:
        branches: [ "main" ]
        tags:
            - 'v*.*.*'
    pull_request:
        branches: [ "main" ]

permissions:
    contents: write

jobs:
    build-ubuntu:
        runs-on: ubuntu-24.04
        env:
            LANG: C.UTF-8
            LC_ALL: C.UTF-8
        container:
            image: docker.io/ubuntu:24.04

        steps:
            -   name: Install dependencies
                run: |
                    apt update -y
                    apt install -y git ninja-build make cmake pkg-config xxd gcc g++ mold dpkg-dev libarchive-dev

            -   uses: actions/checkout@v4

            -   name: Build
                run: |
                    git config --global --add safe.directory "$GITHUB_WORKSPACE"
                    git submodule update --init --recursive
                    make package

            -   name: Install Test
                working-directory: build/release/packages
                run: |
                    dpkg -i *.deb
                    camus -v
                    camus -iIw /tmp/site
                    camus -idw /tmp/site

            -   name: Upload
                uses: actions/upload-artifact@v4
                with:
                    name: Ubuntu-Artifacts
                    path: build/release/packages
                    if-no-files-found: error

    build-macos:
        runs-on: macos-14
        steps:
            -   name: Install dependencies
                run: |
                    brew update
                    brew install git make cmake pkg-config ninja llvm@21 libarchive

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Build
                run: |
                    git config --global --add safe.directory "$GITHUB_WORKSPACE"
                    git submodule update --init --recursive
                    make package

            -   name: Install Test
                working-directory: build/release/packages
                run: |
                    sudo installer -pkg *.pkg -target /
                    camus -v
                    camus -iIw /tmp/site
                    camus -idw /tmp/site

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: MacOS-Artifacts
                    path: build/release/packages
                    if-no-files-found: error

    release:
        runs-on: ubuntu-24.04
        needs: [ build-macos, build-ubuntu ]
        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v4
                with:
                    path: packages
                    merge-multiple: true

            -   name: List artifact
                working-directory: packages
                run: ls -l

            -   name: Release ${{ github.ref_name }}
                uses: softprops/action-gh-release@v3
                if: github.ref_type == 'tag'
                with:
                    name: Release ${{ github.ref_name }}
                    files: |
                        packages/*.dmg
                        packages/*.pkg
                        packages/*.rpm
                        packages/*.deb
                        packages/*.exe
