name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    container:
      image: docker.io/ubuntu:24.04

    steps:
    - name: Install dependencies
      run: |
        apt update -y
        apt install -y git ninja-build make cmake gcc g++ mold dpkg-dev 

    - uses: actions/checkout@v4

    - name: Build
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git submodule update --init --recursive
        make package

    - name: Install Test
      run: |
        dpkg -i build/release/packages/*.deb
        /usr/local/bin/camus -v
        /usr/local/bin/camus -d example

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Ubuntu-Artifacts
        path: build/release/packages
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install git make cmake ninja gcc@13

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git submodule update --init --recursive
          make package

      - name: Install Test
        run: |
          sudo installer -pkg build/release/packages/*.pkg -target / 
          /usr/local/bin/camus -v
          /usr/local/bin/camus -d example

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Artifacts
          path: build/release/packages
          if-no-files-found: error

  release:
    runs-on: ubuntu-24.04
    needs: [ build-macos, build-ubuntu ]
    steps:
      -   name: Download artifact
          uses: actions/download-artifact@v4
          with:
            path: packages
            merge-multiple: true

      - name: list
        run: ls -l

      -   name: Release
          uses: softprops/action-gh-release@v3
          if: github.ref_type == 'tag'
          with:
            files: |
              packages/*.dmg
              packages/*.pkg
              packages/*.deb
